#!/bin/bash

echo "Please run this script from a local git repo!!!!!"
echo "Are you running this script from a local repo? (y/n)"
read RESP
if [[ ${RESP} == "y" || ${RESP} == "Y" ]]; then
    echo "Enter your Github Username: "
    read User
    echo "Enter Repository name: "
    read REPO
    echo "Did you want to keep it private? (true/false)"
    read RESP
    echo "Enter your Github Personal Access Token: " 
    read -s G_TOKEN
    curl -i -H "Authorization: token ${G_TOKEN}" -d "{\"name\":\"${REPO}\", \"private\":\"${RESP}\"}" https://api.github.com/user/repos
    retCode=$?
    if [ ${retCode} -eq 0 ]; then
	echo "Remote repo successfully created."
	echo "Do you want to connect your local repo to this remote repo? (y/n)"
	read RESP
	if [[ ${RESP} == "y" || ${RESP} == "Y" ]]; then
	    git remote add origin https://github.com/"${User}"/"${REPO}".git
	    retCode=$?
	    if [ ${retCode} -eq 0 ]; then
		echo "Remote repo successfully connected with Local repo."
	    else
		echo "Error in connecting remote repo with local repo !!!"
	    fi
	else
	    echo "Exiting Script..."
	fi    
    else
	echo "Error in creating Remote repository !!!"
    fi	
else
    echo "Exting Script..."
fi
