#!/bin/bash

create_repo() {
	if [ ${RESP} == "true" ]; then
		echo "Repository will be private !!"
		curl -f -s -H "Authorization: token ${GIT_TOKEN}" -d "{\"name\":\"${REPO}\", \"private\":\"${RESP}\"}" https://api.github.com/user/repos
    else
		echo "Repository will be public !!"
		curl -f -s -H "Authorization: token ${GIT_TOKEN}" -d "{\"name\":\"${REPO}\"}" https://api.github.com/user/repos
    fi
	retCode=$?
	if [ ${retCode} -eq 0 ]; then
		echo "Remote repo successfully created."    
    else
		echo "Error in creating Remote repository !!!"
        rm $HOME/.cache/crepo/git_passwd
    fi
}

check_pwd() {
    if [ -f "$HOME/.cache/crepo/git_passwd" ]; then
        read -p "Previous GitHub Personal Access Token exist ! Do you want to use that (Y/N) ? " pt
        if [[ ${pt} == "y" || ${pt} == "Y" ]]; then
            GIT_TOKEN=`cat $HOME/.cache/crepo/git_passwd | perl -e 'chomp($encoded=<>); chomp($passwd=unpack("u",$encoded)); print "$passwd\n"'`
        else
            read -sp "Enter your GitHub Personal Access Token: " GIT_TOKEN
            echo ""
        fi
    else
        mkdir -p $HOME/.cache/crepo
        read -sp "Enter your GitHub Peronal Access Token: " GIT_TOKEN
        echo ""
        printf '%s\n' "$GIT_TOKEN" | perl -e 'chomp($passwd=<>); chomp($encoded=pack("u",$passwd));print "$encoded\n"' > $HOME/.cache/crepo/git_passwd
    fi
}

echo "=======CREPO(GitHub Remote Repo creation Script)======="
read -p "Enter your Github Username: " User
read -p "Enter Repository name: " REPO
read -p "Did you want to keep it private? (true/false)" RESP
check_pwd
if [[ $(pwd) = $(git rev-parse --show-toplevel) ]]; then
    create_repo $GIT_TOKEN $REPO $RESP
	
    if [ ${retCode} -eq 0 ]; then
		echo "Do you want to connect your local repo to this remote repo? (y/n)"
		read RES
		if [[ ${RES} == "y" || ${RES} == "Y" ]]; then
	    	git remote add origin https://github.com/"${User}"/"${REPO}".git
	    	retCode=$?
	    	if [ ${retCode} -eq 0 ]; then
				echo "Remote repo successfully connected with Local repo."
	    	else
				echo "Error in connecting remote repo with local repo !!!"
	    	fi
		else
			echo "You could check your repo at: https://github.com/${User}/${REPO}.git"
	    	echo "Exiting Script..."
			exit 0
		fi    
    else
		exit 1
    fi	
else
    echo "You are not running this script from local git repository, you'll not be able to connect the created remote repo to local repo!!!"
	echo "Do you want to continue? (y/n)"
	read RES
	if [[ ${RES} == "y" || ${RES} == "Y" ]]; then
		create_repo $GIT_TOKEN $REPO $RESP
		if [ ${retCode} -eq 0 ]; then
			echo "You could check your repo at: https://github.com/${User}/${REPO}.git"
	    	echo "Exiting Script..."
			exit 0
		else
			exit 1
		fi
	else
		echo "Exiting Script..."
		exit 0
	fi
fi
