#!/bin/bash

create_repo() {
	if [ ${RESP} == "true" ]; then
		echo "Respond is ${RESP}"
		curl -f -i -H "Authorization: token ${GIT_TOKEN}" -d "{\"name\":\"${REPO}\", \"private\":\"${RESP}\"}" https://api.github.com/user/repos
    else
		echo "Respond is ${RESP}"
		curl -f -i -H "Authorization: token ${GIT_TOKEN}" -d "{\"name\":\"${REPO}\"}" https://api.github.com/user/repos
    fi
	retCode=$?
	if [ ${retCode} -eq 0 ]; then
		echo "Remote repo successfully created."    
    else
		echo "Error in creating Remote repository !!!"
    fi
}

echo "=======CREPO(GitHub Remote Repo creation Script)======="
read -p "Enter your Github Username: " User
read -p "Enter Repository name: " REPO
read -p "Did you want to keep it private? (true/false)" RESP
read -sp "Enter your Github Personal Access Token: " GIT_TOKEN 
echo ""
if [[ $(pwd) = $(git rev-parse --show-toplevel) ]]; then
    create_repo $GIT_TOKEN $REPO $RESP
	
    if [ ${retCode} -eq 0 ]; then
		echo "Do you want to connect your local repo to this remote repo? (y/n)"
		read RES
		if [[ ${RES} == "y" || ${RES} == "Y" ]]; then
	    	git remote add origin https://github.com/"${User}"/"${REPO}".git
	    	retCode=$?
	    	if [ ${retCode} -eq 0 ]; then
				echo "Remote repo successfully connected with Local repo."
	    	else
				echo "Error in connecting remote repo with local repo !!!"
	    	fi
		else
			echo "You could check your repo at: https://github.com/${User}/${REPO}.git"
	    	echo "Exiting Script..."
			exit 0
		fi    
    else
		exit 1
    fi	
else
    echo "You are not running this script from local git repository, you'll not be able to connect the created remote repo to local repo!!!"
	echo "Do you want to continue? (y/n)"
	read RES
	if [[ ${RES} == "y" || ${RES} == "Y" ]]; then
		create_repo $GIT_TOKEN $REPO $RESP
		if [ ${retCode} -eq 0 ]; then
			echo "You could check your repo at: https://github.com/${User}/${REPO}.git"
	    	echo "Exiting Script..."
			exit 0
		else
			exit 1
		fi
	else
		echo "Exiting Script..."
		exit 0
	fi
fi
